name: Build Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter pillow numpy scikit-learn

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico --name="PixelArtConverter" app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PixelArtConverter-Windows
          path: dist/PixelArtConverter.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter pillow numpy scikit-learn

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name="PixelArtConverter" app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PixelArtConverter-Linux
          path: dist/PixelArtConverter

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter pillow numpy scikit-learn

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name="PixelArtConverter" app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PixelArtConverter-macOS
          path: dist/PixelArtConverter
